"use client";

import React from "react";
import { useLang } from "../context/LangContext";

const aboutTranslations = {
    es: {
        title: "Soy un Desarrollador Full Stack especializado en JavaScript",
        paragraph1: `
            Tengo una sólida experiencia en React, Node.js, Sequelize, PostgreSQL y Prisma. 
            También tengo habilidades en GIT/GitHub, Unity y Blender. Mi formación 
            multidisciplinaria me ha dotado de habilidades analíticas excepcionales, 
            que potencian mi desempeño como desarrollador.
        `,
        experienceTitle: "Experiencia Laboral",
        experience1Title: "Full Stack Developer - Henry Bootcamp",
        experience1Description: [
            "Desarrollo backend (Node.js, Prisma, PostgreSQL) en el proyecto Chilling Time.",
            "Colaboración en el diseño del frontend y la producción de contenido para la página del proyecto.",
        ],
        experience2Title: "Evaluador de Código - RemoteTasks",
        experience2Description: [
            "Evaluación de código generado por IA y respuestas relacionadas con desarrollo web.",
        ],
        technologiesTitle: "Tecnologías",
        technologies: [
            "Frontend: React, HTML, CSS, JavaScript",
            "Backend: Node.js, Express.js, Prisma, PostgreSQL",
            "Bases de datos: PostgreSQL",
            "Control de versiones: GIT/GitHub",
            "Herramientas: Unity, Blender",
        ],
        valueTitle: "¡Quiero aportar valor a tu equipo!",
        valueMessage: `
            Contáctame para conversar sobre cómo mis habilidades y experiencia pueden 
            contribuir a tus proyectos.
        `,
    },
    en: {
        title: "I am a Full Stack Developer specialized in JavaScript",
        paragraph1: `
            I have solid knowledge in React, Node.js, Sequelize, PostgreSQL, and Prisma. 
            I also have skills in GIT/GitHub, Unity, and Blender. My multidisciplinary 
            background has provided me with exceptional analytical skills, which enhance 
            my performance as a developer.
        `,
        experienceTitle: "Professional Experience",
        experience1Title: "Full Stack Developer - Henry Bootcamp",
        experience1Description: [
            "Backend development (Node.js, Prisma, PostgreSQL) for the Chilling Time project.",
            "Collaboration on the design of the frontend and content production for the project page.",
        ],
        experience2Title: "Code Evaluator - RemoteTasks",
        experience2Description: [
            "Evaluation of code generated by AI and web development related responses.",
        ],
        technologiesTitle: "Technologies",
        technologies: [
            "Frontend: React, HTML, CSS, JavaScript",
            "Backend: Node.js, Express.js, Prisma, PostgreSQL",
            "Databases: PostgreSQL",
            "Version control: GIT/GitHub",
            "Tools: Unity, Blender",
        ],
        valueTitle: "I want to add value to your team!",
        valueMessage: `
            Contact me to discuss how my skills and experience can contribute to your projects.
        `,
    },
};

const About: React.FC = () => {
    const { lang } = useLang();
    const translation = aboutTranslations[lang];

    return (
        <section className="relative p-5 bg-black bg-opacity-70 text-white overflow-x-hidden overflow-y-auto box-border">
            <h2 className="text-3xl mb-4">{translation.title}</h2>

            <div className="max-h-[30vh] md:max-h-full">
                <p className="text-xl mb-6">{translation.paragraph1}</p>

                <section className="mt-6">
                    <h3 className="text-xl font-medium mb-4">
                        {translation.experienceTitle}
                    </h3>

                    <ul className="space-y-4">
                        <li>
                            <h4 className="text-xl font-medium">
                                {translation.experience1Title}
                            </h4>
                            <div className="ml-4">
                                <ul className="list-disc pl-5 text-lg">
                                    {translation.experience1Description.map(
                                        (desc, idx) => (
                                            <li key={idx}>{desc}</li>
                                        )
                                    )}
                                </ul>
                            </div>
                        </li>
                        <li>
                            <h4 className="text-xl font-medium">
                                {translation.experience2Title}
                            </h4>
                            <div className="ml-4">
                                <ul className="list-disc pl-5 text-lg">
                                    {translation.experience2Description.map(
                                        (desc, idx) => (
                                            <li key={idx}>{desc}</li>
                                        )
                                    )}
                                </ul>
                            </div>
                        </li>
                    </ul>
                </section>

                <section className="mt-6">
                    <h3 className="text-xl font-medium mb-4">
                        {translation.technologiesTitle}
                    </h3>

                    <ul className="flex flex-wrap text-lg">
                        {translation.technologies.map((tech, idx) => (
                            <li key={idx} className="mr-4 mb-2">
                                {tech}
                            </li>
                        ))}
                    </ul>
                </section>

                <section className="mt-6">
                    <h3 className="text-xl font-medium mb-4">
                        {translation.valueTitle}
                    </h3>

                    <p className="text-lg">{translation.valueMessage}</p>
                </section>
            </div>
        </section>
    );
};

export default About;
